spring:
  application:
    name: dragonwoo
  datasource:
    url: jdbc:postgresql://localhost:5432/project_db
    username: yo_db
    password: codeclick
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false

server:
  port: 8085
  error:
    include-message: always

# Logging 설정
logging:
  level:
    root: INFO
    com.example: DEBUG

# Swagger 설정 (사용하는 경우)
# 경우swagger:
#  api-info:
#    title: My API
#    description: API for my application
#    version: 1.0.0

# Custom 설정 (필요에 따라 추가)
# custom:
#  property1: value1
#  property2: value2
